import type { Claim, Hyperedge, Observation, Reference, Substance, Tag } from "./types";

// Original summaries of the cited primary studies and official labels. These are
// sourced drafts; the curation date does not imply independent clinical review.
const reviewedAt = "2026-09-29";
const modafinilLabel = "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3b8d1c32-dac9-50e6-e063-6394a90aa5a5";
const methylphenidateLabel = "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c0bf0835-6a2f-4067-a158-8b86c4b0668a";
const methylphenidatePkLabel = "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=effd952d-ac94-47bb-b107-589a4934dcca";
const diphenhydramineLabel = "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=75f0cde5-c419-416d-9c13-bfc03bd83b1d";
const pm = (id: string) => `https://pubmed.ncbi.nlm.nih.gov/${id}/`;
const paper = (id: string, title: string, authors: string, year: number, pmid: string, doi: string | undefined, kind: string, insight: string, limitation: string, funding = "Not assessed in this draft."): Reference => ({ id, title, authors, year, pmid, doi, url: pm(pmid), kind, insight, limitation, funding });
const label = (id: string, title: string, authors: string, url: string, insight: string): Reference => ({ id, title, authors, year: 2026, url, kind: "Official prescribing label", insight, limitation: "Formulation-specific labeling; date denotes retrieval, not original approval. It does not establish benefit outside the labeled context.", funding: "Manufacturer prescribing information hosted by the US National Library of Medicine." });
const identity = (cid: number, name: string): Reference => ({ id: "pubchem", title: `${name}: compound identity and structure`, authors: "NCBI PubChem", year: 2026, url: `https://pubchem.ncbi.nlm.nih.gov/compound/${cid}`, kind: "Chemical database", insight: "Source of the displayed formula, molecular weight, structure and connectivity SMILES.", limitation: "The parent compound identity is distinct from salts, formulations and commercial product quality.", funding: "US National Library of Medicine." });
const entityId = (id: string) => `${["modafinil", "methylphenidate", "diphenhydramine", "citicoline"].includes(id) ? "substance" : "tag"}:${id}`;
const claim = (id: string, assertion: string, relation: string, participants: [string, string][], context: string, sourceIds: string[], limitation: string): Claim => ({ id, assertion, relation, participants: participants.map(([id, role]) => ({ entityId: entityId(id), role })), context, sourceIds, conflictingSourceIds: [], assessment: "not-formally-assessed", limitation });
const observation = (conceptId: string, name: string, direction: Observation["direction"], description: string, sourceId: string, population: string, exposure: string, instrument: string | null = null, magnitude: string | null = null): Observation => ({ conceptId, name, direction, evidence: "Human research", description, sourceId, population, exposure, instrument, magnitude });

export const additionalTags: Tag[] = [
  { id: "histamine", label: "Histamine", aliases: ["hystamine"], kind: "neurotransmitter", description: "A signaling molecule acting at histamine receptors; effects depend on receptor and tissue.", sourceUrls: [pm("15790419")] },
  { id: "histamine-h1", label: "Histamine H1 receptor", kind: "target", description: "A histamine receptor targeted by H1 antihistamines; distinguish it from muscarinic receptor activity.", sourceUrls: [pm("15790419")], relatedIds: ["histamine", "antihistamine"] },
  { id: "muscarinic-receptor", label: "Muscarinic acetylcholine receptors", kind: "target", description: "An acetylcholine receptor family distinct from nicotinic receptors. Antagonism can reduce secretions and produce other anticholinergic effects.", sourceUrls: [pm("15790419")], relatedIds: ["acetylcholine"] },
  { id: "dopamine-transporter", label: "Dopamine transporter", aliases: ["DAT"], kind: "target", description: "A membrane transporter involved in dopamine reuptake. Human PET studies can measure occupancy without establishing general cognitive benefit.", sourceUrls: [pm("9766762"), pm("19293415")], relatedIds: ["dopamine"] },
  { id: "dopamine", label: "Dopamine", kind: "neurotransmitter", description: "A neurotransmitter whose extracellular availability is influenced by dopamine transporters. Increased signaling is not a universal benefit.", sourceUrls: [pm("19293415")], relatedIds: ["dopamine-transporter"] },
  { id: "wakefulness", label: "Wakefulness", kind: "effect", description: "The experience of being awake rather than sleepy. Reported wakefulness is distinct from performance and measured ability to remain awake.", sourceUrls: [pm("16079371")], relatedIds: ["wake-maintenance", "sleep"] },
  { id: "drowsiness", label: "Drowsiness", kind: "effect", description: "A subjective tendency toward sleep. Reports of drowsiness and laboratory performance can diverge.", sourceUrls: [pm("9702844"), diphenhydramineLabel], relatedIds: ["sleep"] },
  { id: "episodic-memory", label: "Episodic memory", kind: "outcome", description: "Memory for associations and events, operationalized here through a specified cognitive test rather than a general memory score.", sourceUrls: [pm("33978188")] },
  { id: "wake-maintenance", label: "Measured wakefulness", kind: "outcome", description: "Sleep latency or wake-maintenance measurements under defined laboratory conditions; not interchangeable with subjective alertness.", sourceUrls: [pm("16079371")], relatedIds: ["wakefulness"] },
  { id: "stroke-recovery", label: "Stroke recovery", kind: "outcome", description: "Functional and neurological recovery after stroke, measured using specified clinical scales and follow-up.", sourceUrls: [pm("22691567")] },
  { id: "antihistamine", label: "Antihistamine", kind: "class", description: "Compounds that inhibit histamine receptor signaling. Receptor selectivity and additional actions differ across drugs.", sourceUrls: [pm("15790419")], relatedIds: ["histamine", "histamine-h1"] },
  { id: "choline-precursor", label: "Choline precursor", kind: "mechanism", description: "A compound supplying choline through metabolism. This biochemical relationship does not itself establish a cognitive outcome.", sourceUrls: [pm("20501174")] },
  { id: "age-exposure", label: "Age context", kind: "exposure", description: "Age-defined study groups can differ in drug disposition. Age associations need study-specific interpretation.", sourceUrls: [pm("2391399"), pm("9702844")] },
];

export const additionalSubstances: Substance[] = [
  {
    slug: "modafinil", name: "Modafinil", subtitle: "Wakefulness and its limits.",
    summary: "A wake-promoting medicine studied in diagnosed sleep disorders. Measured wakefulness, felt alertness and everyday performance are different outcomes.",
    description: "Modafinil is a racemic medicine used for excessive sleepiness in defined clinical settings. Human imaging links it to dopamine transporter occupancy. Sleep-disorder trials do not establish a broad cognitive benefit in healthy, rested people.",
    aliases: ["Provigil"], formula: "C15H15NO2S", molecularWeight: "273.4 g/mol", pubchemCid: 4236, smiles: "C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)N", category: "Wake-promoting medicine", tags: ["stimulant", "dopamine-transporter", "dopamine", "wakefulness", "wake-maintenance"], accent: "#bea17c",
    evidenceNote: "Clinical and mechanistic findings are shown separately. Each claim remains a sourced draft.", reviewedAt, editorialStatus: "sourced-draft",
    halfLife: { label: "About 15 hours", low: 15, high: 15, context: "Effective half-life after repeated oral exposure; R- and S-modafinil have different kinetics.", sourceId: "modafinil-label", observationId: "modafinil-repeat" },
    pkObservations: [{ id: "modafinil-repeat", analyte: "Modafinil (racemate; effective repeated-dose estimate)", route: "Oral", formulation: "Tablet", population: "Adults in prescribing-label pharmacokinetic studies", endpoint: "elimination-half-life", statistic: "approximate", value: 15, low: null, high: null, unit: "hours", context: "Repeated exposure; this effective estimate does not describe both enantiomers independently.", sourceId: "modafinil-label", modelEligible: false }],
    kinetics: { onset: "Not established here", peak: "Plasma peak at 2–4 hours after oral administration", duration: "Not inferred from elimination half-life", bioavailability: "Absolute oral bioavailability not determined in the label", metabolism: "Hepatic metabolism; enantiomers differ in disposition", sourceId: "modafinil-label" }, modifiers: [],
    doses: [{ label: "Shift-work sleep-disorder trial", amount: "200 mg per studied shift", quantity: 200, quantityMax: null, unit: "mg", ingredient: "Modafinil", formulation: "Oral study medication", route: "Oral", frequency: "Before each night-work shift", duration: "3 months", population: "209 adults with shift-work sleep disorder", purpose: "Evaluate excessive sleepiness during night work", sourceCategory: "research", note: "Study exposure, not a regimen for self-directed sleep deprivation.", sourceId: "czeisler2005" }],
    effects: [observation("wakefulness", "Reported wakefulness", "Increased", "Participants reported reduced sleepiness, although substantial residual sleepiness remained.", "czeisler2005", "Patients with shift-work sleep disorder", "200 mg before studied shifts for 3 months", null)],
    outcomes: [observation("wake-maintenance", "Nighttime sleep latency", "Increased", "Laboratory sleep latency improved modestly relative to placebo; wakefulness did not normalize.", "czeisler2005", "Patients with shift-work sleep disorder", "200 mg before studied shifts for 3 months", "Multiple Sleep Latency Test")],
    claims: [claim("modafinil-dat", "Modafinil occupied dopamine transporters in a human imaging experiment.", "transporter-occupancy", [["modafinil", "substance"], ["dopamine-transporter", "target"], ["dopamine", "transmitter"]], "Healthy male participants in an acute PET experiment", ["volkow2009"], "Target occupancy is not a clinical outcome and the selected sample limits generalization.")],
    mechanisms: [{ title: "Dopamine transporter interaction", description: "PET measurements support transporter occupancy and altered extracellular dopamine in the studied men.", sourceId: "volkow2009", conceptId: "dopamine-transporter" }],
    cautions: [{ title: "Serious hypersensitivity", description: "The label warns about serious rash and hypersensitivity reactions.", sourceId: "modafinil-label" }, { title: "Interactions and psychiatric effects", description: "Prescribing information describes psychiatric reactions and interactions, including reduced effectiveness of steroidal contraceptives.", sourceId: "modafinil-label" }, { title: "Residual sleepiness", description: "Improvement in a sleep-disorder trial did not restore normal alertness for every participant.", sourceId: "czeisler2005" }],
    references: [label("modafinil-label", "PROVIGIL: prescribing information", "Teva Pharmaceuticals", modafinilLabel, "Formulation-specific pharmacokinetics, warnings and interaction information."), paper("czeisler2005", "Modafinil for excessive sleepiness associated with shift-work sleep disorder", "Czeisler et al.", 2005, "16079371", "10.1056/NEJMoa041292", "Randomized placebo-controlled trial", "Improved some sleepiness and performance measures during night work.", "Selected clinical population; residual impairment remained. A correction is linked by the publisher.", "Not assessed in this draft; consult the full article disclosures."), paper("volkow2009", "Effects of modafinil on dopamine and dopamine transporters in the male human brain: clinical implications", "Volkow et al.", 2009, "19293415", "10.1001/jama.2009.351", "Human PET study", "Measured dopamine transporter occupancy and changes in extracellular dopamine.", "Small male-only mechanistic study; cannot establish general cognitive efficacy.", "NIH and other research support listed in the publication record."), identity(4236, "Modafinil")], legal: [],
  },
  {
    slug: "methylphenidate", name: "Methylphenidate", subtitle: "A transporter target, a clinical context.",
    summary: "A stimulant medicine with formulation-dependent delivery. ADHD treatment findings and attention-task results should retain their population and exposure context.",
    description: "Methylphenidate is used in clinical treatment of ADHD and narcolepsy. It inhibits catecholamine reuptake, including dopamine transporters. The displayed structure is the parent compound; study and labeled products commonly contain its hydrochloride salt.",
    aliases: ["Ritalin", "Concerta", "MPH"], formula: "C14H19NO2", molecularWeight: "233.31 g/mol", pubchemCid: 4158, smiles: "COC(=O)C(C1CCCCN1)C2=CC=CC=C2", category: "Stimulant medicine", tags: ["stimulant", "dopamine-transporter", "dopamine", "attention"], accent: "#b4a0c3",
    evidenceNote: "A treatment response in ADHD does not establish cognitive enhancement in people without ADHD.", reviewedAt, editorialStatus: "sourced-draft",
    halfLife: { label: "Mean about 3.5 hours", low: 3.5, high: 3.5, context: "Adult immediate-release tablet estimate reported in the Ritalin LA label; formulation controls delivery separately.", sourceId: "methylphenidate-pk-label", observationId: "methylphenidate-ir-mean" },
    pkObservations: [{ id: "methylphenidate-ir-mean", analyte: "Methylphenidate", route: "Oral", formulation: "Immediate-release Ritalin tablet", population: "Adults in label pharmacokinetic studies", endpoint: "elimination-half-life", statistic: "study-mean", value: 3.5, low: null, high: null, unit: "hours", context: "Approximate adult mean; distinct from the reported range and from extended-release delivery duration.", sourceId: "methylphenidate-pk-label", modelEligible: true }, { id: "methylphenidate-ir-range", analyte: "Methylphenidate", route: "Oral", formulation: "Immediate-release Ritalin tablet", population: "Adults in label pharmacokinetic studies", endpoint: "elimination-half-life", statistic: "reported-range", value: null, low: 1.3, high: 7.7, unit: "hours", context: "Reported adult range, not a confidence interval or a personal prediction.", sourceId: "methylphenidate-pk-label", modelEligible: false }],
    kinetics: { onset: "Not established here", peak: "About 2 hours after the label's 10 mg immediate-release tablet exposure", duration: "Depends on formulation; not assigned from plasma half-life", bioavailability: "Enantiomer-specific and affected by first-pass metabolism; no single value assigned here", metabolism: "Primarily de-esterification to ritalinic acid", sourceId: "methylphenidate-label" }, modifiers: [],
    doses: [{ label: "Adult ADHD cognitive-task experiment", amount: "30 mg once", quantity: 30, quantityMax: null, unit: "mg", ingredient: "Methylphenidate", formulation: "Oral study medication; salt not specified in abstract", route: "Oral", frequency: "Single study exposure", duration: "Acute crossover experiment", population: "24 adults recruited from an ADHD clinic; 18 met DSM-IV ADHD criteria", purpose: "Assess attention and spatial working memory", sourceCategory: "research", note: "A monitored experimental exposure, not a dosing recommendation or a formulation conversion.", sourceId: "turner2005" }],
    effects: [], outcomes: [observation("attention", "Sustained attention", "Increased", "Attention-task performance improved in the subgroup meeting ADHD diagnostic criteria. Participants without that diagnosis showed a different response pattern.", "turner2005", "Adults meeting DSM-IV ADHD criteria within a clinic-recruited study", "Single 30 mg oral study exposure", "Sustained-attention task; instrument details not assessed in this draft")],
    claims: [claim("methylphenidate-dat", "Oral methylphenidate occupied dopamine transporters in a PET study.", "transporter-occupancy", [["methylphenidate", "substance"], ["dopamine-transporter", "target"], ["dopamine", "transmitter"]], "Acute exposure in healthy volunteers", ["volkow1998"], "Mechanistic imaging does not measure clinical response.")],
    mechanisms: [{ title: "Dopamine transporter blockade", description: "Human PET detected dose-dependent transporter occupancy after oral administration.", sourceId: "volkow1998", conceptId: "dopamine-transporter" }],
    cautions: [{ title: "Misuse, dependence and withdrawal", description: "Prescribing information carries a boxed warning for abuse, misuse and addiction and describes physical dependence and withdrawal.", sourceId: "methylphenidate-label" }, { title: "Cardiovascular and psychiatric context", description: "The label describes cardiovascular and psychiatric risks and monitoring requirements.", sourceId: "methylphenidate-label" }, { title: "Formulations differ", description: "Immediate-release elimination data do not describe the release profile of every extended-release product.", sourceId: "methylphenidate-pk-label" }],
    references: [label("methylphenidate-label", "RITALIN immediate-release tablets: prescribing information", "Novartis Pharmaceuticals", methylphenidateLabel, "Describes immediate-release absorption, metabolism, clinical use and safety."), label("methylphenidate-pk-label", "RITALIN LA: pharmacokinetic comparison with Ritalin tablets", "Novartis Pharmaceuticals", methylphenidatePkLabel, "Separately reports adult mean and range for immediate-release methylphenidate elimination."), paper("turner2005", "Neurocognitive effects of methylphenidate in adult attention-deficit/hyperactivity disorder", "Turner et al.", 2005, "15338103", "10.1007/s00213-004-1993-5", "Randomized placebo-controlled crossover study", "Observed changes in sustained attention and spatial working memory in the diagnosed subgroup.", "Small acute study, with differing diagnostic subgroups; not evidence for universal enhancement."), paper("volkow1998", "Dopamine transporter occupancies in the human brain induced by therapeutic doses of oral methylphenidate", "Volkow et al.", 1998, "9766762", "10.1176/ajp.155.10.1325", "Human PET study", "Directly measured dopamine transporter occupancy after oral methylphenidate.", "Small selected sample and a mechanistic endpoint."), identity(4158, "Methylphenidate")], legal: [],
  },
  {
    slug: "diphenhydramine", name: "Diphenhydramine", subtitle: "Histamine and acetylcholine pathways.",
    summary: "An H1 antihistamine with antimuscarinic and sedative actions. A sedating experience is not equivalent to restorative sleep or preserved performance.",
    description: "Diphenhydramine acts at histamine H1 receptors and has additional antimuscarinic activity. Different exposures and study populations produce different kinetic and subjective findings. The molecular structure represents the parent base, not the hydrochloride salt used in the cited experiment.",
    aliases: ["DPH", "Benadryl", "Dimedrol"], formula: "C17H21NO", molecularWeight: "255.35 g/mol", pubchemCid: 3100, smiles: "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2", category: "Antihistamine", tags: ["antihistamine", "histamine", "histamine-h1", "muscarinic-receptor", "acetylcholine", "drowsiness", "age-exposure"], accent: "#c4978c",
    evidenceNote: "Age differences were observed in one kinetic study but not in another exposure setting; a universal age multiplier is not justified.", reviewedAt, editorialStatus: "sourced-draft",
    halfLife: { label: "Study mean 9.2 hours", low: 9.2, high: 9.2, context: "Young-adult group in a syrup study; the reported variation is not encoded as a range or confidence interval.", sourceId: "simons1990", observationId: "diphenhydramine-young-adult" },
    pkObservations: [{ id: "diphenhydramine-young-adult", analyte: "Diphenhydramine", route: "Oral", formulation: "Syrup", population: "Young-adult group in a study of 21 participants across three age groups", endpoint: "elimination-half-life", statistic: "study-mean", value: 9.2, low: null, high: null, unit: "hours", context: "Group mean after a single 1.25 mg/kg study exposure; not a recommended exposure.", sourceId: "simons1990", modelEligible: true }, { id: "diphenhydramine-older-adult", analyte: "Diphenhydramine", route: "Oral", formulation: "Syrup", population: "Older-adult group in the same age-comparison study", endpoint: "elimination-half-life", statistic: "study-mean", value: 13.5, low: null, high: null, unit: "hours", context: "Group mean after a single 1.25 mg/kg study exposure. Other experiments did not reproduce a significant age effect.", sourceId: "simons1990", modelEligible: true }],
    kinetics: { onset: "Not established here", peak: "Not assessed for the selected syrup study", duration: "Subjective effects and antihistamine activity differ from serum elimination", bioavailability: "Not assessed in this draft", metabolism: "Not assessed in this draft", sourceId: "simons1990" },
    modifiers: [{ label: "Age-defined study group", effect: "Longer mean half-life in older adults in one study", detail: "A separate lower-exposure crossover experiment did not find significant age differences. Do not use a fixed age-based multiplier.", sourceId: "simons1990", observationId: "diphenhydramine-older-adult", factorType: "other", direction: "variable" }],
    doses: [{ label: "Sedation and performance experiment", amount: "25 mg once", quantity: 25, quantityMax: null, unit: "mg", ingredient: "Diphenhydramine hydrochloride", formulation: "Oral study medication", route: "Oral", frequency: "Single study exposure", duration: "24-hour observation", population: "37 younger and older adult volunteers", purpose: "Assess pharmacokinetics, self-rated sedation and performance", sourceCategory: "research", note: "This particular experiment detected no significant sedation or performance difference versus placebo.", sourceId: "scavone1998" }],
    effects: [observation("drowsiness", "Self-rated sedation", "Variable", "No significant difference from placebo was detected at this study exposure. This does not negate sedation warnings for the medicine.", "scavone1998", "Younger and older healthy volunteers", "Single 25 mg oral exposure", "Self-ratings of sedation")], outcomes: [],
    claims: [claim("diphenhydramine-muscarinic", "Diphenhydramine inhibited muscarinic signaling in an airway-cell experiment.", "receptor-antagonism", [["diphenhydramine", "substance"], ["muscarinic-receptor", "target"], ["acetylcholine", "transmitter"]], "Cultured swine airway mucus-gland cells", ["liu2005"], "Preclinical tissue assay; it does not quantify human cognitive effects."), { ...claim("diphenhydramine-age", "One experiment found age-group differences in diphenhydramine elimination.", "clearance-context", [["diphenhydramine", "substance"], ["age-exposure", "population-context"]], "Syrup study compared younger adults, older adults and children", ["simons1990"], "A separate lower-exposure study found no significant age effect."), conflictingSourceIds: ["scavone1998"] }],
    mechanisms: [{ title: "H1 antihistamine activity", description: "Diphenhydramine inhibits histamine-mediated responses; its additional muscarinic activity makes it pharmacologically broader than an H1-only description.", sourceId: "liu2005", conceptId: "histamine-h1" }, { title: "Antimuscarinic activity", description: "Experimental inhibition of acetylcholine-driven secretion supports a distinct antimuscarinic mechanism.", sourceId: "liu2005", conceptId: "muscarinic-receptor" }],
    cautions: [{ title: "Sedation and additive impairment", description: "The label warns about drowsiness and additive effects with alcohol and other CNS depressants.", sourceId: "diphenhydramine-label" }, { title: "Anticholinergic effects", description: "Drying effects and urinary or ocular problems matter in susceptible people; consult the formulation's contraindications and warnings.", sourceId: "diphenhydramine-label" }, { title: "Age is not a personal half-life calculator", description: "Contrasting experiments caution against assigning every older adult the same elimination estimate.", sourceId: "scavone1998" }],
    references: [label("diphenhydramine-label", "Diphenhydramine hydrochloride capsules: prescribing information", "DailyMed label record", diphenhydramineLabel, "Documents antihistamine, anticholinergic and sedative properties and related warnings."), paper("simons1990", "Diphenhydramine: pharmacokinetics and pharmacodynamics in elderly adults, young adults, and children", "Simons et al.", 1990, "2391399", "10.1002/j.1552-4604.1990.tb01871.x", "Human pharmacokinetic study", "Compared serum elimination and skin-test responses across age groups.", "Small groups and a particular syrup exposure; group means do not predict individual clearance."), paper("scavone1998", "Pharmacokinetics and pharmacodynamics of diphenhydramine 25 mg in young and elderly volunteers", "Scavone et al.", 1998, "9702844", "10.1002/j.1552-4604.1998.tb04466.x", "Randomized placebo-controlled crossover study", "Did not detect significant age effects on kinetics or sedation differences at the tested exposure.", "An undetected difference in one acute experiment does not establish absence of impairment in other settings.", "NIMH support is listed in the PubMed record; other funding not assessed."), paper("liu2005", "Effects of first and second generation antihistamines on muscarinic induced mucus gland cell ion transport", "Liu et al.", 2005, "15790419", "10.1186/1471-2210-5-8", "Preclinical receptor-function experiment", "Compared antihistamine and antimuscarinic actions in airway cells.", "Swine cell preparation; cannot determine human clinical benefit or harm magnitude."), identity(3100, "Diphenhydramine")], legal: [],
  },
  {
    slug: "citicoline", name: "Citicoline", subtitle: "A precursor, with outcome-specific evidence.",
    summary: "CDP-choline is studied as a source of choline and in neurological outcomes. A positive memory-task finding does not establish broad neuroprotection.",
    description: "Citicoline participates in choline-related metabolism. Research spans healthy older adults with memory complaints and people with neurological disease. These populations, endpoints and treatment contexts must remain separate. Radiolabel disposition is not a parent-drug elimination curve.",
    aliases: ["CDP-choline", "Cytidine diphosphate choline", "Cytidine 5′-diphosphocholine"], formula: "C14H26N4O11P2", molecularWeight: "488.32 g/mol", pubchemCid: 13804, smiles: "C[N+](C)(C)CCOP(=O)([O-])OP(=O)(O)OCC1C(C(C(O1)N2C=CC(=NC2=O)N)O)O", category: "Choline precursor", tags: ["choline-precursor", "episodic-memory", "stroke-recovery"], accent: "#a9b993",
    evidenceNote: "Memory-task and stroke-recovery findings differ. This draft does not assign a general cognition or neuroprotection score.", reviewedAt, editorialStatus: "sourced-draft",
    halfLife: { label: "Not established here", low: null, high: null, context: "Available tracer disposition includes metabolites and tissue pathways; no parent-citicoline half-life is assigned.", sourceId: "dinsdale1983", observationId: "citicoline-unresolved" },
    pkObservations: [{ id: "citicoline-unresolved", analyte: "Unchanged citicoline", route: "Oral", formulation: "Radiolabeled study compound", population: "Healthy adult volunteers", endpoint: "elimination-half-life", statistic: "not-established", value: null, low: null, high: null, unit: "hours", context: "Measured radioactivity follows parent-derived material, not specifically unchanged citicoline; no decay model is justified.", sourceId: "dinsdale1983", modelEligible: false }],
    kinetics: { onset: "Not established here", peak: "Tracer radioactivity has multiple peaks; not treated as a parent-compound plasma peak", duration: "Not established here", bioavailability: "Radiolabel absorption does not establish unchanged parent-compound bioavailability", metabolism: "Extensive transformation and incorporation into biosynthetic pathways", sourceId: "dinsdale1983" }, modifiers: [],
    doses: [{ label: "Memory-task trial", amount: "500 mg/day", quantity: 500, quantityMax: null, unit: "mg", ingredient: "Citicoline", formulation: "Study capsules", route: "Oral", frequency: "Once daily with breakfast", duration: "12 weeks", population: "100 adults aged 50–85 with age-associated memory impairment", purpose: "Compare memory-test changes with placebo", sourceCategory: "research", note: "Selected population and study formulation; not evidence for benefit in all ages.", sourceId: "nakazaki2021" }],
    effects: [], outcomes: [observation("episodic-memory", "Paired-associate memory", "Increased", "A secondary episodic-memory endpoint improved relative to placebo. Clinical importance and generalizability remain uncertain.", "nakazaki2021", "Older adults with age-associated memory impairment", "500 mg/day for 12 weeks", "Cambridge Brain Sciences Paired Associate test"), observation("stroke-recovery", "Global recovery after stroke", "Variable", "ICTUS found no significant recovery advantage over placebo and was stopped for futility.", "davalos2012", "Adults with moderate-to-severe acute ischemic stroke", "Hospital trial: intravenous followed by oral citicoline", "Global endpoint combining NIHSS, modified Rankin Scale and Barthel Index at 90 days", "Odds ratio 1.03; 95% CI 0.86–1.25")],
    claims: [claim("citicoline-choline", "Administered citicoline is converted into circulating metabolites including choline.", "metabolic-precursor", [["citicoline", "substance"], ["choline-precursor", "mechanism"]], "Human and animal metabolism experiments distinguished parent compound from metabolites", ["lopez1987"], "Metabolite availability alone does not establish a memory benefit.")],
    mechanisms: [{ title: "Precursor metabolism", description: "Measurements after administration support conversion to choline and cytidine; the parent compound and its metabolites require separate interpretation.", sourceId: "lopez1987", conceptId: "choline-precursor" }],
    cautions: [{ title: "Disease outcomes do not transfer", description: "The large ICTUS trial did not demonstrate improved recovery after moderate-to-severe acute stroke.", sourceId: "davalos2012" }, { title: "Limited safety horizon", description: "A short trial in selected older adults does not establish long-term safety across all populations.", sourceId: "nakazaki2021" }],
    references: [paper("nakazaki2021", "Citicoline and Memory Function in Healthy Older Adults: A Randomized, Double-Blind, Placebo-Controlled Clinical Trial", "Nakazaki et al.", 2021, "33978188", "10.1093/jn/nxab119", "Randomized placebo-controlled trial", "Found improvement in secondary episodic and composite memory endpoints.", "Selected older population, short follow-up and secondary endpoints; not a broad cognitive-enhancement result.", "Ingredient-supplier involvement is reported; full funding disclosures require editorial review."), paper("davalos2012", "Citicoline in the treatment of acute ischaemic stroke: an international, randomised, multicentre, placebo-controlled study (ICTUS trial)", "Dávalos et al.", 2012, "22691567", "10.1016/S0140-6736(12)60813-7", "Multicentre randomized placebo-controlled trial", "Did not demonstrate a recovery advantage in moderate-to-severe acute ischemic stroke.", "A clinical stroke population and hospital treatment sequence; findings do not resolve healthy-memory questions.", "Ferrer Grupo."), paper("dinsdale1983", "Pharmacokinetics of 14C CDP-choline", "Dinsdale et al.", 1983, "6412727", undefined, "Human radiolabel-disposition study", "Tracked absorption and elimination of radiolabeled material through multiple pathways.", "Small study; radioactivity includes metabolites and cannot define a parent-drug half-life."), paper("lopez1987", "Metabolism of cytidine (5′)-diphosphocholine (CDP-choline) following oral and intravenous administration to the human and the rat", "López-Coviella et al.", 1987, "20501174", "10.1016/0197-0186(87)90049-0", "Human and animal metabolism study", "Distinguished unchanged compound from circulating choline and cytidine.", "Mechanistic disposition findings do not demonstrate cognitive efficacy."), identity(13804, "Citicoline")], legal: [],
  },
];

const graphRelationships: Hyperedge[] = [
  { id: "modafinil-dopamine-transporter", label: "Modafinil and dopamine transport", relation: "transporter-occupancy", members: ["modafinil", "dopamine-transporter", "dopamine"], memberRoles: { modafinil: "substance", "dopamine-transporter": "target", dopamine: "transmitter" }, description: "Acute PET findings in healthy men; target occupancy is distinct from a clinical outcome.", sourceUrl: pm("19293415") },
  { id: "methylphenidate-dopamine-transporter", label: "Methylphenidate and dopamine transport", relation: "transporter-occupancy", members: ["methylphenidate", "dopamine-transporter", "dopamine"], memberRoles: { methylphenidate: "substance", "dopamine-transporter": "target", dopamine: "transmitter" }, description: "Oral administration produced transporter occupancy in a human PET study.", sourceUrl: pm("9766762") },
  { id: "diphenhydramine-histamine-h1", label: "Histamine receptor antagonism", relation: "receptor-antagonism", members: ["diphenhydramine", "histamine-h1", "histamine"], memberRoles: { diphenhydramine: "substance", "histamine-h1": "target", histamine: "transmitter" }, description: "H1 antihistamine activity is distinct from the compound's antimuscarinic actions.", sourceUrl: pm("15790419") },
  { id: "diphenhydramine-muscarinic-context", label: "Antimuscarinic activity in an airway assay", relation: "receptor-antagonism", members: ["diphenhydramine", "muscarinic-receptor", "acetylcholine"], memberRoles: { diphenhydramine: "substance", "muscarinic-receptor": "target", acetylcholine: "transmitter" }, description: "Swine airway-cell assay; the result does not quantify human cognitive effects.", sourceUrl: pm("15790419") },
  { id: "diphenhydramine-age-context", label: "Age and elimination: contrasting studies", relation: "clearance-context", members: ["diphenhydramine", "age-exposure"], memberRoles: { diphenhydramine: "substance", "age-exposure": "population-context" }, description: "Age-group differences in one syrup study were not replicated in a lower-exposure experiment; no universal age multiplier is assigned.", sourceUrl: pm("2391399"), sourceUrls: [pm("2391399"), pm("9702844")] },
  { id: "citicoline-precursor-metabolism", label: "Citicoline precursor metabolism", relation: "metabolic-precursor", members: ["citicoline", "choline-precursor"], memberRoles: { citicoline: "substance", "choline-precursor": "mechanism" }, description: "Conversion to circulating metabolites does not itself establish a cognitive benefit.", sourceUrl: pm("20501174") },
  { id: "citicoline-memory-context", label: "Memory task in selected older adults", relation: "outcome-observation", members: ["citicoline", "episodic-memory", "age-exposure"], memberRoles: { citicoline: "substance", "episodic-memory": "measured-outcome", "age-exposure": "population-context" }, description: "Secondary memory-task improvement in older adults with age-associated memory impairment; not a general memory claim.", sourceUrl: pm("33978188") },
];

export const additionalHyperedges: Hyperedge[] = graphRelationships.map((edge) => ({ ...edge, members: edge.members.map(entityId), memberRoles: Object.fromEntries(Object.entries(edge.memberRoles).map(([id, role]) => [entityId(id), role])) }));
