import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, FlaskConical, GitBranch } from "lucide-react";
import Catalog from "@/components/catalog";
import KnowledgeGraph from "@/components/knowledge-graph";
import { getCatalog, getConcepts, getKnowledgeGraph } from "@/lib/repository";
import { conceptPath } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function Home({searchParams}: {searchParams:Promise<{tag?:string;q?:string}>}) {
  const {tag,q}=await searchParams;
  const [substances,tags,graph]=await Promise.all([getCatalog(),getConcepts(),getKnowledgeGraph({focus:"caffeine",limit:40})]);
  return <main id="main" className="home-page"><section className="home-intro"><div className="intro-copy"><div className="intro-kicker"><span className="status-dot"/> AN INDEPENDENT, OPEN REFERENCE</div><h1>A field guide<br/>to <em>substances.</em></h1><p>Understand the effects. Explore the mechanisms.<br className="desktop-break"/> Read the evidence, with its context intact.</p><div className="intro-foot"><span><BookOpen size={15}/> Shared knowledge</span><span><FlaskConical size={15}/> Traceable sources</span><span><GitBranch size={15}/> Connected concepts</span></div></div><Link href="/substances/caffeine" className="featured-note"><div className="featured-note-label"><FlaskConical size={15}/> A CLOSER LOOK</div><div className="featured-molecule"><img src="/molecules/caffeine.png" alt="Caffeine molecular structure"/><span className="molecule-orbit orbit-one"/><span className="molecule-orbit orbit-two"/></div><div className="featured-note-bottom"><div><span>From adenosine to elimination.</span><strong>Explore caffeine <ArrowUpRight size={17}/></strong></div><span className="formula-label">C₈H₁₀N₄O₂</span></div></Link></section><div className="home-columns"><Catalog key={`${tag || "all"}:${q||""}`} substances={substances} tags={tags} initialTag={tags.some(t=>t.id===tag)?tag:""} initialQuery={typeof q==="string"?q:""}/><aside className="home-sidebar"><section className="graph-preview"><div className="sidebar-card-heading"><span className="eyebrow">FOLLOW A CONNECTION</span><GitBranch size={17}/></div><h3>One substance.<br/>Many relationships.</h3><p>Explore an effect, a receptor, or the context behind a finding.</p><div className="mini-graph"><KnowledgeGraph {...graph} compact/></div><Link href="/graph" className="graph-preview-link">Open the knowledge graph <ArrowUpRight size={16}/></Link></section><section className="concept-index-card"><span className="eyebrow">START WITH A CONCEPT</span>{["acetylcholine","histamine","cyp1a2","tobacco-smoke"].map(id=>tags.find(t=>t.id===id)).filter(t=>t!==undefined).map(t=><Link key={t.id} href={conceptPath(t)}><span>{t.label}<small>{t.kind.replaceAll("-"," ")}</small></span><ArrowUpRight size={15}/></Link>)}</section><section className="reading-note"><span className="eyebrow">READING THE EVIDENCE</span><h3>The finding.<br/>And its limits.</h3><p>A subjective experience, a laboratory result, and a clinical outcome answer different questions.</p><Link href="/about">How this wiki is written <ArrowRight size={14}/></Link></section></aside></div></main>;
}
